version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    image: php-composer/server
    container_name: laquale-server
    ports:
      - "8080:8080"
    volumes:
      - ".:/var/www/html/"
    command: php -S 0.0.0.0:8080 -t public/
